name: Deploy app

on:
  release:
    types: [published]

env:
  API_KEY: ${{ secrets.API_KEY }}
  API_URL: ${{ secrets.API_URL }}
  SOCKET_URL: ${{ secrets.SOCKET_URL }}
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2
        
      - name: 🔧 Create .env file
        run: echo "Creating the .env file..." && touch .env && echo "API_URL=env:API_URL \nAPI_KEY=env:API_KEY \nSOCKET_URL=env:SOCKET_URL" > .env && echo "Done!"

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Publish app
        run: expo publish 
